---
debug: true
server:
  address: ":9090"
context:
  timeout: 2
filesystem:
  relativePath: "uploads"
database:
  params:
    parseTime: "true"
  host: localhost
  port: 3306
  user: user
  password: password
  dbname: ems_api
  allowNativePasswords: true
  max_open_connections: 25
  max_idle_connections: 25
  max_connections_lifetime: 5
auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 604800
